name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Exract metadata
      #   id: meta
      #   uses: docker/metadata-action
      #   with:
      #     images: ghcr.io/${{ github.repository_owner }}/foodcal:$(date +%s)


      - name: Build the Docker image
        id: push
        uses: docker/build-push-action
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: latest, $(date +%s)
          

      # - name: Push the Docker image
      #   run: docker push ghcr.io/${{ github.repository_owner }}/foodcal:$(date +%s)

    