name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build the Docker image
        run: docker build . -t ghcr.io/${{ github.repository_owner }}/foodcal:latest

      - name: Tag the Docker image
        run: docker tag ghcr.io/${{ github.repository_owner }}/foodcal latest

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/foodcal:latest

    